language: node_js
 node_js: node
 cache:
   directories:
     - node_modules
notifications:
  email:
    recipients:
      - klick5000@gmail.com
      - coracardoni@gmail.com
    on_success: always
    on_failure: always